import os
import weaviate
from weaviate.classes.query import Filter
from typing import TypedDict
from dotenv import load_dotenv

from langgraph.graph import StateGraph, END
from langgraph.checkpoint.memory import MemorySaver
from langchain_aws import ChatBedrock

load_dotenv()

# --- 1. State Definition ---
class SentioState(TypedDict):
    user_query: str
    user_id: str      
    category: str     
    context: str
    analysis: str
    reflection_count: int
    is_cached: bool
    final_output: str

# --- 2. AWS Bedrock Setup ---
llm = ChatBedrock(
    model_id="amazon.nova-micro-v1:0",
    model_kwargs={"temperature": 0},
    region_name=os.getenv("AWS_REGION", "us-east-1")
)

# --- 3. Nodes ---

def cache_check_node(state: SentioState):
    client = weaviate.connect_to_local(port=int(os.getenv("WEAVIATE_PORT", 8081)))
    try:
        cache = client.collections.get("SentioCache")
        result = cache.query.near_text(
            query=state["user_query"], 
            limit=1,
            filters=Filter.by_property("user_id").equal(state["user_id"])
        )
        
        if result.objects:
            return {"final_output": result.objects[0].properties["response"], "is_cached": True}
        return {"is_cached": False}
    finally:
        client.close()

def researcher_node(state: SentioState):
    client = weaviate.connect_to_local(port=int(os.getenv("WEAVIATE_PORT", 8081)))
    try:
        vault = client.collections.get("SentioTransaction")
        response = vault.query.near_text(
            query=state["user_query"],
            limit=15,
            filters=Filter.all_of([
                Filter.by_property("user_id").equal(state["user_id"]),
                Filter.by_property("category").equal(state["category"])
            ])
        )

        transactions = []
        total_cognitive_load = 0.0
        count = len(response.objects)

        if count == 0:
            return {
                "context": f"No historic transaction data records isolated for Target User {state['user_id']} within category context room: {state['category']}.", 
                "reflection_count": 0
            }

        for o in response.objects:
            props = o.properties
            amount = props.get("amount", 0.0)
            t_type = props.get("transaction_type", "Debit")
            cognitive_load = float(props.get("cognitive_load_score", 0.0))
            
            transactions.append(f"- Amount: ${amount}, Type: {t_type}, Cognitive Load: {cognitive_load}")
            total_cognitive_load += cognitive_load

        avg_cognitive_load = total_cognitive_load / count
        structured_context = f"Calculated Metrics:\n- Average Cognitive Load Score: {avg_cognitive_load:.2f}\n- Total Record Count: {count}\n\n"
        structured_context += "Transaction Details:\n" + "\n".join(transactions)

        return {"context": structured_context, "reflection_count": 0}
    finally:
        client.close()

def analyzer_node(state: SentioState):
    prompt = (
        f"You are Sentio, an expert financial HCI agent analyzing data for User: {state['user_id']}.\n\n"
        f"Context & Calculated Metrics:\n{state['context']}\n\n"
        f"User Query: {state['user_query']}\n\n"
        "Instructions:\n"
        "1. Summarize spending and transaction trends strictly using the data provided.\n"
        "2. Evaluate the 'Average Cognitive Load Score'. If it is high (>0.7), you must explicitly "
        "conclude your analysis with concrete stress-reduction advice."
    )
    res = llm.invoke(prompt)
    return {"analysis": res.content}

def reflection_node(state: SentioState):
    prompt = (
        f"Critique this analysis: '{state['analysis']}'\n"
        f"Based ONLY on this data: {state['context']}\n\n"
        "Rules:\n1. Verify math.\n2. Ensure the advice matches the category requested.\n"
        "3. Keep it concise."
    )
    res = llm.invoke(prompt)
    return {"analysis": res.content, "reflection_count": state["reflection_count"] + 1}

def save_cache_node(state: SentioState):
    """Saves output generated by the reflection agent loop back into our Vector Cache."""
    client = weaviate.connect_to_local(port=int(os.getenv("WEAVIATE_PORT", 8081)))
    try:
        cache = client.collections.get("SentioCache")
        output_to_save = state.get("analysis") or state.get("final_output")
        
        cache.data.insert(properties={
            "user_id": state["user_id"],
            "query": state["user_query"],
            "response": output_to_save
        })
        return {"final_output": output_to_save}
    finally:
        client.close()

# --- 4. Routing & Graph Construction ---

def should_reflect(state: SentioState):
    return "reflect" if state["reflection_count"] < 1 else "save_cache"

def cache_router(state: SentioState):
    return END if state["is_cached"] else "research"

builder = StateGraph(SentioState)
builder.add_node("cache", cache_check_node)
builder.add_node("research", researcher_node)
builder.add_node("analyze", analyzer_node)
builder.add_node("reflect", reflection_node)
builder.add_node("save_cache", save_cache_node)

builder.set_entry_point("cache")
builder.add_conditional_edges("cache", cache_router, {"research": "research", END: END})
builder.add_edge("research", "analyze")
builder.add_conditional_edges("analyze", should_reflect, {"reflect": "reflect", "save_cache": "save_cache"})
builder.add_edge("reflect", "save_cache")
builder.add_edge("save_cache", END)

memory = MemorySaver()
sentio_app = builder.compile(checkpointer=memory)